services:
  - type: web
    name: newhope-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --no-input
    startCommand: daphne school_management.asgi:application --port $PORT --bind 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: newhope-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: .onrender.com
    healthCheckPath: /
    autoDeploy: true